# Generated by Django 5.1.15 on 2026-09-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorapp', '0060_game_consul_for_life_appointed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='category',
            field=models.CharField(blank=True, choices=[('battle', 'Battle')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='log',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
